name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Adjust if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Generate deployment package
        run: |
          cd publish
          zip -r ../deploy-package.zip .


      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MyDotNetApp           # Your EB Application name
          environment_name: MyDotNetApp-env       # Your EB Environment name
          version_label: v-${{ github.run_number }}
          region: eu-north-1                       # Your AWS region
          deployment_package: deploy-package.zip
